Source/DevCDRServer/Core31/DevCDR_Server_Core31/Controllers/DevCDRController.cs
using DevCDR.Extensions;
using jaindb;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.AspNetCore.SignalR;
using Microsoft.Extensions.Caching.Memory;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Reflection;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Threading.Tasks;

namespace DevCDRServer.Controllers
{
    [Authorize]
    public class DevCDRController : Controller
    {
        private readonly IHubContext<Default> _hubContext;
        private readonly IWebHostEnvironment _env;
        private IMemoryCache _cache;
        private WebClient webclient = new WebClient();
        public DevCDR.Extensions.AzureLogAnalytics AzureLog = new DevCDR.Extensions.AzureLogAnalytics("", "", "");
        public static string RootName = (Environment.GetEnvironmentVariable("rootKey") ?? "DeviceCommander");
        public DevCDRController(IHubContext<Default> hubContext, IWebHostEnvironment env, IMemoryCache memoryCache)
        {
            _hubContext = hubContext;
            _env = env;
            _cache = memoryCache;

            try
            {
                Type xType = Type.GetType("DevCDRServer.Default");

                MemberInfo[] memberInfos = xType.GetMember("wwwrootPath", BindingFlags.Public | BindingFlags.Static);
                ((FieldInfo)memberInfos[0]).SetValue(new string(""), _env.WebRootPath);
            }
            catch { }


            if (string.IsNullOrEmpty(AzureLog.WorkspaceId))
            {
                if (!string.IsNullOrEmpty(Environment.GetEnvironmentVariable("Log-WorkspaceID")) && !string.IsNullOrEmpty(Environment.GetEnvironmentVariable("Log-SharedKey")))
                {
                    AzureLog = new DevCDR.Extensions.AzureLogAnalytics(Environment.GetEnvironmentVariable("Log-WorkspaceID"), Environment.GetEnvironmentVariable("Log-SharedKey"), "DevCDR_" + (Environment.GetEnvironmentVariable("INSTANCENAME") ?? "Default"));
                    //AzureLog.PostAsync(new { Computer = Environment.MachineName, EventID = 0001, Description = "DevCDRController started" });
                }
            }
        }
        public static string lastalert = "";
        private readonly object __lockObj = new object();

        [AllowAnonymous]
        public ActionResult Dashboard()
        {
            ViewBag.Title = "Dashboard " + Environment.GetEnvironmentVariable("INSTANCETITLE");
            ViewBag.Instance = Environment.GetEnvironmentVariable("INSTANCENAME");
            ViewBag.appVersion = typeof(DevCDRController).Assembly.GetCustomAttribute<AssemblyFileVersionAttribute>().Version;
            ViewBag.Route = "/chat";

            int itotalDeviceCount = -1;

            itotalDeviceCount = new JainDBController(_env, _cache).totalDeviceCount(Path.Combine(_env.WebRootPath, "jaindb\\_Chain"));

            int iDefault = ClientCount("Default");
            int iOnlineCount = iDefault;
            int iOfflineCount = itotalDeviceCount - iOnlineCount;

            if (iOfflineCount < 0)
                iOfflineCount = 0;

            if (iOnlineCount > itotalDeviceCount)
                itotalDeviceCount = iOnlineCount;

            ViewBag.TotalDeviceCount = itotalDeviceCount;
            ViewBag.OnlineDeviceCount = iOnlineCount;
            ViewBag.OfflineDeviceCount = iOfflineCount;
            ViewBag.TotalDefault = iDefault;
            return View();
        }

#if DEBUG
        [AllowAnonymous]
#endif
        [Authorize]
        public ActionResult Default()
        {
            ViewBag.Title = Environment.GetEnvironmentVariable("INSTANCETITLE") ?? "Default Environment";
            ViewBag.Instance = Environment.GetEnvironmentVariable("INSTANCENAME") ?? "Default";
            ViewBag.appVersion = typeof(DevCDRController).Assembly.GetCustomAttribute<AssemblyFileVersionAttribute>().Version;
            ViewBag.Endpoint = Request.GetEncodedUrl().Split("/DevCDR/Default")[0] + "/chat";
            ViewBag.Customer = Environment.GetEnvironmentVariable("CUSTOMERID") ?? "DEMO";


            if (!string.IsNullOrEmpty(Environment.GetEnvironmentVariable("fnDevCDR")))
            {
                if (System.IO.File.Exists(Path.Combine(_env.WebRootPath, "DevCDRAgentCoreNew.msi")))
                    ViewBag.InstallCMD = $"&msiexec -i { Request.GetEncodedUrl().Split("/DevCDR/Default")[0] + "/DevCDRAgentCoreNew.msi" } CUSTOMER={ViewBag.Customer} ENDPOINT={Request.GetEncodedUrl().Split("/DevCDR/Default")[0] + "/chat"}  /qn REBOOT=REALLYSUPPRESS";
                else
                    ViewBag.InstallCMD = $"&msiexec -i https://devcdrcore.azurewebsites.net/DevCDRAgentCoreNew.msi CUSTOMER={ViewBag.Customer} ENDPOINT={Request.GetEncodedUrl().Split("/DevCDR/Default")[0] + "/chat"} /qn REBOOT=REALLYSUPPRESS";
            }
            else
            {
                if (System.IO.File.Exists(Path.Combine(_env.WebRootPath, "DevCDRAgentCoreNew.msi")))
                    ViewBag.InstallCMD = $"&msiexec -i { Request.GetEncodedUrl().Split("/DevCDR/Default")[0] + "/DevCDRAgentCoreNew.msi" } ENDPOINT={Request.GetEncodedUrl().Split("/DevCDR/Default")[0] + "/chat"} /qn REBOOT=REALLYSUPPRESS";
                else
                    ViewBag.InstallCMD = $"&msiexec -i https://devcdrcore.azurewebsites.net/DevCDRAgentCoreNew.msi ENDPOINT={Request.GetEncodedUrl().Split("/DevCDR/Default")[0] + "/chat"} /qn REBOOT=REALLYSUPPRESS";
            }
            ViewBag.Route = "/chat";

            var sRoot = Directory.GetCurrentDirectory();
            if (System.IO.File.Exists(Path.Combine(sRoot, "wwwroot/plugin_ContextMenu.cshtml")))
            {
                ViewBag.Menu = System.IO.File.ReadAllText(Path.Combine(sRoot, "wwwroot/plugin_ContextMenu.cshtml"));
                ViewBag.ExtMenu = true;
            }

            if (string.IsNullOrEmpty(Environment.GetEnvironmentVariable("IP2LocationURL")))
            {
                ViewBag.Location = "Internal IP";
            }
            else
            {
                ViewBag.Location = "Location";
            }
            return View();
        }

        //[AllowAnonymous]
        //public ActionResult Frame()
        //{
        //    ViewBag.Title = Environment.GetEnvironmentVariable("INSTANCETITLE") ?? "Default Environment";
        //    ViewBag.Instance = Environment.GetEnvironmentVariable("INSTANCENAME") ?? "Default";
        //    ViewBag.appVersion = typeof(DevCDRController).Assembly.GetCustomAttribute<AssemblyFileVersionAttribute>().Version;
        //    ViewBag.Endpoint = Request.GetEncodedUrl().Split("/DevCDR/Default")[0] + "/chat";
        //    ViewBag.Customer = Environment.GetEnvironmentVariable("CUSTOMERID") ?? "DEMO";


        //    if (!string.IsNullOrEmpty(Environment.GetEnvironmentVariable("fnDevCDR")))
        //    {
        //        if (System.IO.File.Exists(Path.Combine(_env.WebRootPath, "DevCDRAgentCoreNew.msi")))
        //            ViewBag.InstallCMD = $"&msiexec -i { Request.GetEncodedUrl().Split("/DevCDR/Default")[0] + "/DevCDRAgentCoreNew.msi" } CUSTOMER={ViewBag.Customer} ENDPOINT={Request.GetEncodedUrl().Split("/DevCDR/Default")[0] + "/chat"}  /qn REBOOT=REALLYSUPPRESS";
        //        else
        //            ViewBag.InstallCMD = $"&msiexec -i https://devcdrcore.azurewebsites.net/DevCDRAgentCoreNew.msi CUSTOMER={ViewBag.Customer} ENDPOINT={Request.GetEncodedUrl().Split("/DevCDR/Default")[0] + "/chat"} /qn REBOOT=REALLYSUPPRESS";
        //    }
        //    else
        //    {
        //        if (System.IO.File.Exists(Path.Combine(_env.WebRootPath, "DevCDRAgentCoreNew.msi")))
        //            ViewBag.InstallCMD = $"&msiexec -i { Request.GetEncodedUrl().Split("/DevCDR/Default")[0] + "/DevCDRAgentCoreNew.msi" } ENDPOINT={Request.GetEncodedUrl().Split("/DevCDR/Default")[0] + "/chat"} /qn REBOOT=REALLYSUPPRESS";
        //        else
        //            ViewBag.InstallCMD = $"&msiexec -i https://devcdrcore.azurewebsites.net/DevCDRAgentCoreNew.msi ENDPOINT={Request.GetEncodedUrl().Split("/DevCDR/Default")[0] + "/chat"} /qn REBOOT=REALLYSUPPRESS";
        //    }
        //    ViewBag.Route = "/chat";

        //    var sRoot = Directory.GetCurrentDirectory();
        //    if (System.IO.File.Exists(Path.Combine(sRoot, "wwwroot/plugin_ContextMenu.cshtml")))
        //    {
        //        ViewBag.Menu = System.IO.File.ReadAllText(Path.Combine(sRoot, "wwwroot/plugin_ContextMenu.cshtml"));
        //        ViewBag.ExtMenu = true;
        //    }

        //    if (string.IsNullOrEmpty(Environment.GetEnvironmentVariable("IP2LocationURL")))
        //    {
        //        ViewBag.Location = "Internal IP";
        //    }
        //    else
        //    {
        //        ViewBag.Location = "Location";
        //    }
        //    return View();
        //}

        [AllowAnonymous]
        public ActionResult About()
        {
            ViewBag.Message = "Device Commander details...";
            ViewBag.appVersion = typeof(DevCDRController).Assembly.GetCustomAttribute<AssemblyFileVersionAttribute>().Version;

            return View();
        }

        [AllowAnonymous]
        public ActionResult GetVersion()
        {
            return Content(typeof(DevCDRController).Assembly.GetCustomAttribute<AssemblyFileVersionAttribute>().Version);
        }

        [AllowAnonymous]
        public ActionResult Contact()
        {
            ViewBag.Message = "Device Commander Contact....";
            ViewBag.appVersion = typeof(DevCDRController).Assembly.GetCustomAttribute<AssemblyFileVersionAttribute>().Version;

            return View();
        }


        [AllowAnonymous]

Source/DevCDRServer/Core31/DevCDR_Server_Core31/Views/Shared/_CustomPS.cshtml
<div class="row">
    <div class="form-group  col-12">
        <label>Custom PowerShell Command:</label>
        <textarea class="form-control" style="min-width: 100%; font-family: 'Courier New'" id="psScript" rows="4"></textarea>
        <small id="psScriptHelp" class="form-text text-muted">Run a custom PowerShell Script on all selected Devices...</small>
    </div>
    <input class="btn btn-outline-secondary" type="button" onclick="RunPS()" value="Run PowerShell" />
</div>

Source/DevCDRServer/Core31/DevCDR_Server_Core31/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<style type="text/css">
    html {
        position: relative;
        min-height: 100%;
    }

    .footer {
        position: fixed;
        bottom: 0;
        width: 100%;
        /* Set the fixed height of the footer here */
        height: 30px;
        /*background-color: #f5f5f5;*/
        text-align: right;
        padding-right: 100px;
    }
</style>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DevCDR</title>
    <link rel="icon" type="image/x-icon" href="~/favicon.ico">
    @*<environment include="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/css/site.css" />
        </environment>
        <environment exclude="Development">
            <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
            <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        </environment>*@
    @*<link href="~/DataTables/css/select.dataTables.css" rel="stylesheet" />
        <link href="~/DataTables/css/jquery.dataTables.css" rel="stylesheet" />
        <link href="~/DataTables/css/buttons.dataTables.css" rel="stylesheet" />*@
    <link href="~/lib/bootstrap4/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
    <link href="~/lib/datatables.net-select-jqui/css/select.jqueryui.min.css" rel="stylesheet" />
    <link href="~/lib/datatables.net-jqui/dataTables.jqueryui.min.css" rel="stylesheet" />
    <link href="~/lib/datatables.net-buttons-jqui/css/buttons.jqueryui.min.css" rel="stylesheet" />
    <link href="~/lib/jquery-contextmenu/jquery.contextMenu.css" rel="stylesheet" />
    <link href="~/lib/jqueryui/themes/base/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/signalr/dist/browser/signalr.min.js"></script>

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <a asp-area="" asp-controller="DevCDR" asp-action="Default" class="navbar-brand">DevCDR Server Core</a>
        <button class="navbar-toggler" data-toggle="collapse" data-target="#layoutNavbarSupportedContent"
                aria-controls="layoutNavbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="layoutNavbarSupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="DevCDR" asp-action="Default">Devices</a></li>
                <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="DevCDR" asp-action="About">About</a></li>
                <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="DevCDR" asp-action="Contact">Contact</a></li>
            </ul>
            <partial name="_LoginPartial" />
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="body">
        @RenderBody()
        <footer class="footer" style="z-index:-1">
            <p>&copy; 2021 by Roger Zander - Version: @ViewBag.appVersion</p>
        </footer>
    </div>

    <script src="~/lib/bootstrap4/dist/js/bootstrap.min.js"></script>
    <script src="~/lib/modernizr/modernizr.min.js"></script>
    <script src="~/lib/jqueryui/jquery-ui.min.js"></script>

    <script src="~/lib/datatables.net/jquery.dataTables.min.js"></script>
    <script src="~/lib/datatables.net-jqui/dataTables.jqueryui.min.js"></script>
    <script src="~/lib/datatables.net-select/js/dataTables.select.min.js"></script>
    <script src="~/lib/datatables.net-select-jqui/js/select.jqueryui.min.js"></script>
    <script src="~/lib/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/lib/datatables.net-buttons-jqui/js/buttons.jqueryui.min.js"></script>
    <script src="~/lib/ouanalyse-datatables.net-buttons-html5/js/buttons.html5.min.js"></script>
    @*<script src="~/lib/datatables.net-colreorder/js/dataTables.colReorder.min.js"></script>*@
    <script src="~/lib/datatables.net-responsive/dataTables.responsive.min.js"></script>

    @*<script src="~/lib/datatables/jquery.dataTables.min.js"></script>*@
    @*<script src="~/lib/datatables/dataTables.select.min.js"></script>
        <script src="~/lib/datatables/dataTables.buttons.min.js"></script>*@
    @*<script src="~/lib/datatables/buttons.html5.min.js"></script>*@
    <script src="~/lib/jquery-contextmenu/jquery.contextMenu.min.js"></script>
    <script src="~/lib/jquery-contextmenu/jquery.ui.position.min.js"></script>


    @RenderSection("Scripts", required: false)
</body>
</html>

Source/DevCDRServer/Core31/DevCDR_Server_Core31/Views/Shared/_LayoutFrame.cshtml
<!DOCTYPE html>
<style type="text/css">
    html {
        position: relative;
        min-height: 100%;
    }

    .footer {
        position: fixed;
        bottom: 0;
        width: 100%;
        /* Set the fixed height of the footer here */
        height: 30px;
        /*background-color: #f5f5f5;*/
        text-align: right;
        padding-right: 100px;
    }
</style>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ROMAWO</title>
    <link rel="icon" type="image/x-icon" href="~/favicon.ico">
    @*<environment include="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/css/site.css" />
        </environment>
        <environment exclude="Development">
            <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
            <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        </environment>*@
    @*<link href="~/DataTables/css/select.dataTables.css" rel="stylesheet" />
        <link href="~/DataTables/css/jquery.dataTables.css" rel="stylesheet" />
        <link href="~/DataTables/css/buttons.dataTables.css" rel="stylesheet" />*@
    <link href="~/lib/bootstrap4/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
    <link href="~/lib/datatables.net-select-jqui/css/select.jqueryui.min.css" rel="stylesheet" />
    <link href="~/lib/datatables.net-jqui/dataTables.jqueryui.min.css" rel="stylesheet" />
    <link href="~/lib/datatables.net-buttons-jqui/css/buttons.jqueryui.min.css" rel="stylesheet" />
    <link href="~/lib/jquery-contextmenu/jquery.contextMenu.css" rel="stylesheet" />
    <link href="~/lib/jqueryui/themes/base/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/signalr/dist/browser/signalr.min.js"></script>

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <a asp-area="" asp-controller="DevCDR" asp-action="Default" class="navbar-brand">ROMAWO managed workplace</a>
        <button class="navbar-toggler" data-toggle="collapse" data-target="#layoutNavbarSupportedContent"
                aria-controls="layoutNavbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="layoutNavbarSupportedContent">
            @*<ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="DevCDR" asp-action="Default">Devices</a></li>
                <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="DevCDR" asp-action="About">About</a></li>
                <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="DevCDR" asp-action="Contact">Contact</a></li>
            </ul>*@
            @*<partial name="_LoginPartial" />*@
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="body">
        @RenderBody()
        <footer class="footer" style="z-index:-1">
            <p>&copy; 2021 by Zander-Tools - Version: @ViewBag.appVersion</p>
        </footer>
    </div>

    <script src="~/lib/bootstrap4/dist/js/bootstrap.min.js"></script>
    <script src="~/lib/modernizr/modernizr.min.js"></script>
    <script src="~/lib/jqueryui/jquery-ui.min.js"></script>

    @*<script type="text/javascript" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>*@
    @*<script type="text/javascript" src="https://cdn.datatables.net/1.10.20/js/dataTables.jqueryui.min.js"></script>*@
    @*<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.6.1/js/dataTables.buttons.min.js"></script>*@
    @*<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.jqueryui.min.js"></script>*@
    @*<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.colVis.min.js"></script>*@
    @*<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.html5.min.js"></script>*@
    @*<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.print.min.js"></script>*@
    @*<script type="text/javascript" src="https://cdn.datatables.net/select/1.3.1/js/dataTables.select.min.js"></script>*@


    <script src="~/lib/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/datatables.net-jqui/js/dataTables.jqueryui.min.js"></script>
    <script src="~/lib/datatables.net-select/js/dataTables.select.min.js"></script>
    <script src="~/lib/datatables.net-select-jqui/js/select.jqueryui.min.js"></script>
    <script src="~/lib/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/lib/datatables.net-buttons-jqui/js/buttons.jqueryui.min.js"></script>
    <script src="~/lib/ouanalyse-datatables.net-buttons-html5/js/buttons.html5.min.js"></script>
    @*<script src="~/lib/datatables.net-colreorder/js/dataTables.colReorder.min.js"></script>*@
    <script src="~/lib/datatables.net-responsive/js/dataTables.responsive.min.js"></script>

    @*<script src="~/lib/datatables/jquery.dataTables.min.js"></script>*@
    @*<script src="~/lib/datatables/dataTables.select.min.js"></script>
        <script src="~/lib/datatables/dataTables.buttons.min.js"></script>*@
    @*<script src="~/lib/datatables/buttons.html5.min.js"></script>*@
    <script src="~/lib/jquery-contextmenu/jquery.contextMenu.min.js"></script>
    <script src="~/lib/jquery-contextmenu/jquery.ui.position.min.js"></script>


    @RenderSection("Scripts", required: false)
</body>
</html>

Source/DevCDRServer/Core31/DevCDR_Server_Core31/Views/Shared/_RunCommands.cshtml
<script type="text/javascript">
    function Command(param, args) {
        var table = $('#test').DataTable();
        if (args == null) { args = "" };
        var rowdata = JSON.stringify(table.rows({ selected: true }).data().toArray());
        $.ajax({
            type: 'post',
            url: '@Url.Action("Command")',
            data: '{ "command": "' + param + '", "instance" : "@ViewData["Instance"].ToString()", "args": "' + args + '", "rows": ' + rowdata + '  }',
            contentType: 'application/json; charset=utf-8',
            dataType: "json",
        })
    }

    function RunPS(param,title) {
        var table = $('#test').DataTable();
        var rowdata = JSON.stringify(table.rows({ selected: true }).data().toArray());
        if (param == null) { param = psScript.value }
        if (title == null) { title = "CustomPS" }
        $.ajax({
            type: 'post',
            url: '@Url.Action("RunPSCommand")',
            data: '{ "psscript": "' + encodeURIComponent(param) + '", "title" : "' + title + '", "instance" : "@ViewData["Instance"].ToString()", "rows": ' + rowdata + '  }',
            contentType: 'application/json; charset=utf-8',
            dataType: "json",
        })
    }

        function RunPSAsync(param,title) {
        var table = $('#test').DataTable();
        var rowdata = JSON.stringify(table.rows({ selected: true }).data().toArray());
        if (param == null) { param = psScript.value }
        if (title == null) { title = "CustomPS" }
        $.ajax({
            type: 'post',
            url: '@Url.Action("RunPSAsy")',
            data: '{ "psscript": "' + encodeURIComponent(param) + '", "title" : "' + title + '", "instance" : "@ViewData["Instance"].ToString()", "rows": ' + rowdata + '  }',
            contentType: 'application/json; charset=utf-8',
            dataType: "json",
        })
    }

    function InvExp() {
        var table = $('#test').DataTable();
        if (table.rows({ selected: true }).count() > 0) {
            var id = table.rows({ selected: true }).data()[0]["id"];
            var jUrl = "../JainDB/Inv?id=" + id;
            window.open(jUrl); //to open a new tab
            //window.location.href = jUrl;
        };
    }

    function RunUserPS(param,title) {
        var table = $('#test').DataTable();
        var rowdata = JSON.stringify(table.rows({ selected: true }).data().toArray());
        if (param == null) { param = psScript.value }
        if (title == null) { title = "CustomPS" }
        $.ajax({
            type: 'post',
            url: '@Url.Action("RunUserPS")',
            data: '{ "psscript": "' + encodeURIComponent(param) + '", "title" : "' + title + '", "instance" : "@ViewData["Instance"].ToString()", "rows": ' + rowdata + '  }',
            contentType: 'application/json; charset=utf-8',
            dataType: "json",
        })
    }

    function RunPSFile(file,title) {
        var table = $('#test').DataTable();
        var rowdata = JSON.stringify(table.rows({ selected: true }).data().toArray());
        if (title == null) { title = "CustomPS" }
        $.ajax({
            type: 'post',
            url: '@Url.Action("RunPSFile")',
            data: '{ "file": "' + encodeURIComponent(file) + '", "title" : "' + title + '", "instance" : "@ViewData["Instance"].ToString()", "rows": ' + rowdata + '  }',
            contentType: 'application/json; charset=utf-8',
            dataType: "json",
        })
    }
</script>